[[ClassifierRules]]
EnumerationScope = "ShareEnumeration"
RuleName = "KeepDollarShares"
MatchAction = "Snaffle"
Description = "Notifies the user that C$ or ADMIN$ is visible on file share, but doesn't actually scan inside it."
MatchLocation = "ShareName"
WordListType = "Exact"
MatchLength = 0
WordList = ["\\\\C\\$",
"\\\\ADMIN\\$", "ADMIN\\$", "C\\$"]
Triage = "Black"